global:
  kubernetes:
    versions: {}
    upstreamVersions:
      include: false

name: citycloud
type: openstack
enabled: true
kubernetes:
  versions: {}
machineImages:
  - name: ubuntu
    versions:
    - version: 20.4.20210616
      classification: preview
      cri:
      - name: containerd
      - name: docker
    - version: 20.4.20200423
      cri:
      - name: containerd
      - name: docker
machineTypes:
  - cpu: "2"
    gpu: "0"
    memory: 4Gi
    name: 2C-4GB-50GB
    storage:
      class: standard
      type: default
      size: 50Gi
  - cpu: "4"
    gpu: "0"
    memory: 8Gi
    name: 4C-8GB-50GB
    storage:
      class: standard
      type: default
      size: 50Gi
  - cpu: "8"
    gpu: "0"
    memory: 16Gi
    name: 8C-16GB-50GB
    storage:
      class: standard
      type: default
      size: 50Gi
regions:
  - name: Fra1
    zones:
    - name: nova
  - name: Kna1
    zones:
    - name: nova
  - name: Sto2
    zones:
    - name: nova
providerConfig:
  apiVersion: openstack.provider.extensions.gardener.cloud/v1alpha1
  kind: CloudProfileConfig
  machineImages:
  - name: ubuntu
    versions:
    - version: 20.4.20210616
      image: "Ubuntu 20.04 Focal Fossa 20210616"
    - version: 20.4.20200423
      image: "Ubuntu 20.04 Focal Fossa 20200423"
      regions:
        - name: Fra1
          id: 235d9bfb-7a13-4434-9966-cfc0ae033e79
  useOctavia: true
  keystoneURLs:
  - region: Fra1
    url: https://fra1.citycloud.com:5000/v3/
  - region: Kna1
    url: https://kna1.citycloud.com:5000/v3/
  - region: Sto2
    url: https://sto2.citycloud.com:5000/v3/
  constraints:
    floatingPools:
    - name: ext-net
    loadBalancerProviders:
    - name: amphora
