apiVersion: {{ include "priorityclassversion" . }}
kind: PriorityClass
metadata:
  name: gardener-system-critical
  annotations:
    resources.gardener.cloud/mode: Ignore # TODO(kris94) remove in future release
value: 999998950
globalDefault: false
description: "This class is used to ensure that the gardenlet and some seed system components has a high priority and is not preempted in favor of other pods."