{{- if and .Values.global.gardenlet.enabled .Values.global.gardenlet.config.server.https.tls }}
apiVersion: v1
kind: Secret
metadata:
  name: gardenlet-cert
  namespace: garden
  labels:
    app: gardener
    role: gardenlet
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  gardenlet.crt: {{ required ".Values.global.gardenlet.config.server.https.tls.crt is required" (b64enc .Values.global.gardenlet.config.server.https.tls.crt) }}
  gardenlet.key: {{ required ".Values.global.gardenlet.config.server.https.tls.key is required" (b64enc .Values.global.gardenlet.config.server.https.tls.key) }}
{{- end }}
