{{- if and .Values.global.gardenlet.enabled .Values.global.gardenlet.config.gardenClientConnection.kubeconfig }}
apiVersion: v1
kind: Secret
metadata:
  name: gardenlet-kubeconfig-garden
  namespace: garden
  labels:
    app: gardener
    role: gardenlet
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  kubeconfig: {{ .Values.global.gardenlet.config.gardenClientConnection.kubeconfig | b64enc }}
{{- end }}
