global:
  kubernetes:
    versions: {}
    upstreamVersions:
      include: false

name: alicloud
enabled: true
kubernetes:
  versions: {}
machineImages:
  - name: coreos
    versions:
    - version: 2023.4.0
      cri:
      - name: docker
machineTypes:
  - name: ecs.sn2ne.large
    cpu: "2"
    gpu: "0"
    memory: 8Gi
volumeTypes:
  - name: cloud_efficiency
    class: standard
  - name: cloud_ssd
    class: premium
regions:
  - name: eu-central-1
    zones:
    - name: eu-central-1a
    - name: eu-central-1b
providerConfig:
   apiVersion: alicloud.provider.extensions.gardener.cloud/v1alpha1
   kind: CloudProfileConfig
   machineImages:
   - name: coreos
     versions:
     - version: 2023.4.0
       regions:
       - name: eu-central-1
         id: coreos_2023_4_0_64_30G_alibase_20190319.vhd
