- name: "runtime-gvisor"
  repo: "gardener/gardener-extension-runtime-gvisor"
  version: "v0.5.1"
- name: "external-dns-management"
  repo: "gardener/external-dns-management"
  version: "v0.12.7"
- name: "networking-calico"
  repo: "gardener/gardener-extension-networking-calico"
  version: "v1.24.3"
- name: "networking-cilium"
  repo: "gardener/gardener-extension-networking-cilium"
  version: "v1.13.0"
- name: "os-gardenlinux"
  repo: "gardener/gardener-extension-os-gardenlinux"
  version: "v0.12.0"
- name: "os-ubuntu"
  repo: "gardener/gardener-extension-os-ubuntu"
  version: "v1.16.0"
- name: "provider-alicloud"
  repo: "gardener/gardener-extension-provider-alicloud"
  version: "v1.37.0"
- name: "provider-aws"
  repo: "gardener/gardener-extension-provider-aws"
  version: "v1.36.0"
- name: "provider-azure"
  repo: "gardener/gardener-extension-provider-azure"
  version: "v1.28.1"
  additionalCharts:
    - "charts/gardener-extension-admission-azure"
- name: "provider-gcp"
  repo: "gardener/gardener-extension-provider-gcp"
  version: "v1.23.1"
- name: "provider-hcloud"
  repo: "23technologies/gardener-extension-provider-hcloud"
  version: "v0.5.2"
- name: "provider-openstack"
  repo: "gardener/gardener-extension-provider-openstack"
  version: "v1.26.1"
- name: "shoot-cert-service"
  repo: "gardener/gardener-extension-shoot-cert-service"
  version: "v1.23.0"
- name: "shoot-dns-service"
  repo: "gardener/gardener-extension-shoot-dns-service"
  version: "v1.21.0"
