{{- if .Values.global.admission.enabled }}
apiVersion: {{ include "webhookadmissionregistration" . }}
kind: MutatingWebhookConfiguration
metadata:
  name: gardener-admission-controller
webhooks:
- name: audit-policies.gardener.cloud
  admissionReviewVersions: ["v1", "v1beta1"]
  timeoutSeconds: 10
  rules:
    - apiGroups:
        - "core.gardener.cloud"
      apiVersions:
        - "*"
      operations:
        - CREATE
        - UPDATE
      resources:
        - shoots
    - apiGroups:
        - ""
      apiVersions:
        - v1
      operations:
        - UPDATE
      resources:
        - configmaps
  failurePolicy: Fail
  namespaceSelector:
    matchLabels:
      gardener.cloud/role: project
  clientConfig:
    {{- if .Values.global.deployment.virtualGarden.enabled }}
    url: https://gardener-admission-controller.garden/webhooks/audit-policies
    {{- else }}
    service:
      namespace: garden
      name: gardener-admission-controller
      path: /webhooks/audit-policies
    {{- end }}
    caBundle: {{ required ".Values.global.admission.config.server.https.tls.caBundle is required" (b64enc .Values.global.admission.config.server.https.tls.caBundle) }}
  sideEffects: None
{{- end }}
