{{- if and .Values.global.deployment.virtualGarden.enabled .Values.global.scheduler.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ required ".Values.global.scheduler.serviceAccountName is required" .Values.global.scheduler.serviceAccountName }}
  namespace: garden
  labels:
    app: gardener
    role: scheduler
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
{{- end }}
