# Local specific values which override values.yaml

global:
  # Gardener API server configuration values
  apiserver:
    etcd:
      useSidecar: true
    # Don't care about certificates for local development scenario
    insecureSkipTLSVerify: true
    caBundle: ""
    tls:
      crt: |
        -----BEGIN CERTIFICATE-----
        MIIDkjCCAnqgAwIBAgIBAjANBgkqhkiG9w0BAQsFADAVMRMwEQYDVQQDEwptaW5p
        a3ViZUNBMB4XDTE4MDMxMzA3MjUwMFoXDTE5MDMxMzA3MjUwMFowLDEXMBUGA1UE
        ChMOc3lzdGVtOm1hc3RlcnMxETAPBgNVBAMTCG1pbmlrdWJlMIIBIjANBgkqhkiG
        9w0BAQEFAAOCAQ8AMIIBCgKCAQEA2b8eW1Aq0elVVIDNyXJC/qbSnVMqyQhFmI1+
        0ZHH+nuDHtXHHB0QigvD83f6IVolsbC7HAGVsqACX2sgDACx7yHsQzWFogTM+/xj
        f9Z3hdnYEQkaKeJKfmYThH+cbPHdoToVqHVoUIIWrlts8s76Q3QQBfq8kj/pJ60P
        eAnFZpjkf/UbmFlevnl53+YA/Ikk4m6CkEtway0WzPlCtmNOMprSxUb3FkVILOco
        bjf1l+PqlAwoy7mxtaG9BDLIENnI8UbOpC+mJPaVnXsV7JQE/LQMcQN1xL2KsFi7
        9/kDNVbXLlgaQWgy8LZ0+0/k7OpWy57AUiuOF42wYGwG+SbpQwIDAQABo4HVMIHS
        MA4GA1UdDwEB/wQEAwIFoDAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIw
        DAYDVR0TAQH/BAIwADCBkgYDVR0RBIGKMIGHggptaW5pa3ViZUNBgiRrdWJlcm5l
        dGVzLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWyCFmt1YmVybmV0ZXMuZGVmYXVs
        dC5zdmOCEmt1YmVybmV0ZXMuZGVmYXVsdIIKa3ViZXJuZXRlc4IJbG9jYWxob3N0
        hwTAqGNkhwQKYAABhwQKAAABMA0GCSqGSIb3DQEBCwUAA4IBAQA75Pt0rzjMtxME
        4h6GBzeba/QUCFfKtR4gNxV1EcKQwJz2UcVr20yGgGUGyJLyTS7t56ktlWVF2NWD
        7W3M0DNjSY6ELlgGHnU273WiQN8sHrmON/9AqhtElfQ2IbqL3uIMJwn2g3t/5rBn
        SS1r2Y7xLcsJ4tneFa+ARTlx9JlPBjYx7nMZ/Vd6yP6U7BButQGUf/p6F1+vTslM
        bMmq4RmmV4FvzPWNEfFejOV/6Hjm3TrFds2Z3fpGIVQGAmEiT4tb1bHW8AorJ5CR
        fhzQ4+MoUBFMOo3BBnKPmospcGL9NAh81nBbqmzKbzXRi7AlBc+fh/nhDpZMcMqr
        QaZeuq/C
        -----END CERTIFICATE-----
      key: |
        -----BEGIN RSA PRIVATE KEY-----
        MIIEowIBAAKCAQEA2b8eW1Aq0elVVIDNyXJC/qbSnVMqyQhFmI1+0ZHH+nuDHtXH
        HB0QigvD83f6IVolsbC7HAGVsqACX2sgDACx7yHsQzWFogTM+/xjf9Z3hdnYEQka
        KeJKfmYThH+cbPHdoToVqHVoUIIWrlts8s76Q3QQBfq8kj/pJ60PeAnFZpjkf/Ub
        mFlevnl53+YA/Ikk4m6CkEtway0WzPlCtmNOMprSxUb3FkVILOcobjf1l+PqlAwo
        y7mxtaG9BDLIENnI8UbOpC+mJPaVnXsV7JQE/LQMcQN1xL2KsFi79/kDNVbXLlga
        QWgy8LZ0+0/k7OpWy57AUiuOF42wYGwG+SbpQwIDAQABAoIBAEqR9Sd4cPGqYxqp
        cdBHXUIwh3hxfvmR56Oy8Xd74Wya1/C7bZDnMz7TgKvkrri1UqtjxvB0anvd6HId
        EcCKjGVEzNDHh5hQ5JJ3gOvK2uvwCtrqrxcg9DoNYynBOiTlP+1zIu+qJatMoc/c
        Z5dP4s0u9j3V/LZpRMPdtKp7TiswF3ku2jfwNAmSKpMBurVxh7Rx41Ddzk4v6pBn
        MJRiI2RSYoMXbyIz/jFRpJghuqC/EePpaV7iFoYJsjIpBdsnHLd5cn6d/lp2x1qb
        5U2OjO+HuEoHiIn7BRRXl6zIzluZTRHN5jZf5tiu36NEcE9K8x5Jfytz98CXxNCk
        Q5E8iiECgYEA7dWGvy/r2GobY9xXGMMlc+vxbhrjf4PYnidH9KwItbFoeXd5GZ4k
        mBIVuxMDO0YxIfI0B1seW9smRyRBLNQbV1A1EYbjfqwROnqAFtH/6yzjomwwp2iM
        dwIyfIp8mA4hrcalQrb4V1bodEKecH3J9Si9i24yf9uMnJnuzVuiH4UCgYEA6mDP
        3iH0qk6jqXWdzowDUaFhY3L5oUnmR3XP9BLPH6mZkKzozc0i60PWJnsd4k3BWoGB
        HBkyMzkPSB1ou3JAKAHQhMRqQWHAVWrwaZ7v9eGlWLUHJ2b20yydAjHwucKEli86
        HnA5aeXACbsQlkpoNnYRvBDJQAEnYsrnBroIbCcCgYAFfK+nKYvfalNHcoXv5FCw
        4/il+ajWAEy3GWDnnDB3QKiQZNk+Zg+iEoi90Cp665umlNfuc4O3ys6PRZ7bUelv
        kkInLV2CRqX/G2RpIl8tJdP6o1RcCGV1OW/Av9EwEONmBvc5Gs+P9ElYpVDSd5R5
        O39kAB7aJE6SLlr8EekjoQKBgQC1nvnVl5iB1NiMO6Fi6iq0Ogs+xlzc+GgjHg9c
        gqrQTVu7udHZkMorZ3Dudt9Me5aGrO5AuOGmweOurWN4ReujVOyhxZbVPYuOZYUR
        Q+GNNyMrH3UAupAwSlUM22hAepTF0KkH500GW8w5fiU3YUdqVIofox5go8RCkRr/
        om9eZwKBgFqf+3EqR9mgaMZCmon08DzQXxTPITnCtlh1RMqjDPV4rr2ebootARg2
        grZ3BVGluAD/h4gEpteIxwsp+C1sZXMO7GAXwbOuQ+04pnskIoVbtK8Tp6Z4CFBs
        Y0TqA2hEv0a0xSaTn4l9lvVNylPBF4tVOh9MDQo90FYJSS/3O/pg
        -----END RSA PRIVATE KEY-----

  # Gardener admission controller configuration values
  admission:
    config:
      server:
        https:
          bindAddress: 0.0.0.0
          port: 2719
          tls:
            caBundle: |
              -----BEGIN CERTIFICATE-----
              MIIDYDCCAkigAwIBAgIUaa2cFO/CSVrvq8O/0geuMtXLOsIwDQYJKoZIhvcNAQEL
              BQAwSDELMAkGA1UEBhMCVVMxCzAJBgNVBAgTAkNBMRYwFAYDVQQHEw1TYW4gRnJh
              bmNpc2NvMRQwEgYDVQQDEwtleGFtcGxlLm5ldDAeFw0xODA4MTYyMDMyMDBaFw0y
              MzA4MTUyMDMyMDBaMEgxCzAJBgNVBAYTAlVTMQswCQYDVQQIEwJDQTEWMBQGA1UE
              BxMNU2FuIEZyYW5jaXNjbzEUMBIGA1UEAxMLZXhhbXBsZS5uZXQwggEiMA0GCSqG
              SIb3DQEBAQUAA4IBDwAwggEKAoIBAQC5C8/vhXuEyd0fT6blHpkklDbcnurD4K6S
              bFhdLZeGCI+vKW34OtAs8SpAvkJk1/AOgFldPFi7Fa8YmgJCzbGnylFqqrawdBhH
              tVYxCAe14u2Sdiq1sOgurDtQ3Gh+Eu5u+P0l16y0dyQxl4dDtwHfz4jrNVadnWDc
              T/+PPsd46i0+cOYhkDk7R54EuG+1kXakG4sXVpKy1TMwoynrBVh42L3bskqrVnpT
              +gcAzCtoia8XRJ/jhoscXtR0r1tKi3g1J4qA7uX4I9rTsgOBck0exJPRgEmwuO5F
              sZ44E8MIox+FVH9NDTcBdIT95XUlcanHJ+PZkRUXZysiM9lnIjBjAgMBAAGjQjBA
              MA4GA1UdDwEB/wQEAwIBBjAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBQUJU2I
              iCrYttHhNhj5hwsQI+MIljANBgkqhkiG9w0BAQsFAAOCAQEATe93evEAI8mdipdm
              jpFB9+0W3C2kO1/CtBujN3Pveg98lU9pkKiU9WQ/z+bZDWzTzISvV32OVJCmQSzr
              VDRT03cljPiBX9oF577M16O3ZrvPWt1Qz6XzmbOav5bvBWi9iUdLHJm8p6CDHKYX
              IDewlUH8+AFiMtwLer4QdWQRy+0iNdnXB8BbvwBlaqMhRZajw2io7yGZgqWVb9ry
              6Tl6queZZk2NyK3IDmm7a1exLXPR8vSd2QB6bSBMR75p/FmcVCuW642TYNq0QoUs
              W9yT3v1pxQfXki6VLd7/v8BxpNQ3k1V3MKXiK8B08GsD6Ikk9GgMVcdX4ZBemZf3
              0cUD2Q==
              -----END CERTIFICATE-----
            crt: |
              -----BEGIN CERTIFICATE-----
              MIIEEzCCAvugAwIBAgIJAKVcj0hHoSuaMA0GCSqGSIb3DQEBBQUAMEgxCzAJBgNV
              BAYTAlVTMQswCQYDVQQIEwJDQTEWMBQGA1UEBxMNU2FuIEZyYW5jaXNjbzEUMBIG
              A1UEAxMLZXhhbXBsZS5uZXQwHhcNMjAwOTA4MTcyMjQ2WhcNMzAwOTA2MTcyMjQ2
              WjBgMQswCQYDVQQGEwJVUzETMBEGA1UECAwKQ2FsaWZvcm5pYTEWMBQGA1UEBwwN
              U2FuIEZyYW5jaXNjbzERMA8GA1UECgwIZ2FyZGVuZXIxETAPBgNVBAMMCGdhcmRl
              bmVyMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAragksFWulbJPWT/U
              npbtg79pOLzsXF2RIyaUOD0HCk9QlrP8a5ojglzEvuNF8NVZeaj090nFRE51Vnou
              qUgktnaHNwL3fuZcVyl5J66asiskPsfZcxT5nOC1uIegQWa8bSiqnPRbQUX3QNFS
              zA9RmRSTjbRPzBm72Y2grV+vNYysuq1p8l/qs2GDJZTuLpMBYGrWxcmD6bgLy1Um
              gCzK58fFnMR8Muq+jCIPsSD1FMD3Q6FVMXi58pHufxl6UgmzbO0phs5SsBE0mhIX
              2OHx1VHsk/2OH4GKpOBppcyQLdtpxxfsX8Xg6gazVH5G6nT/rFVUM/S+4UJCOYyd
              eQZ/QQIDAQABo4HnMIHkMAkGA1UdEwQCMAAwHQYDVR0OBBYEFAKLcqSN8WadFaaC
              aMgbPTrlPUSBMAsGA1UdDwQEAwIFoDAdBgNVHSUEFjAUBggrBgEFBQcDAgYIKwYB
              BQUHAwEwgYsGA1UdEQSBgzCBgIcEfwAAAYIJbG9jYWxob3N0gh1nYXJkZW5lci1h
              ZG1pc3Npb24tY29udHJvbGxlcoIkZ2FyZGVuZXItYWRtaXNzaW9uLWNvbnRyb2xs
              ZXIuZ2FyZGVugihnYXJkZW5lci1hZG1pc3Npb24tY29udHJvbGxlci5nYXJkZW4u
              c3ZjMA0GCSqGSIb3DQEBBQUAA4IBAQClPcPMvtjLs/XHQZ+AZ8iCC8PJlbFRp6EW
              MABvamp4b/WjC05CM0/bGhxqSTriUHliQsSuxL4LjkX0y9vT1SZlXQ4ukvYh5Nlb
              Ocy/OJH67ulKu+gk45P72ZDE9ctnYGY7CXqPwolPHQDYPfpp9JHlnrhctGwG79UD
              ZAAbhemvzKSoyiKE/PLutGtPvcEoRi9ZDLl/6/BerTUxm1svo00FBqzUla74btuW
              uViZCXagBrBGzjEK1hC6jmD4jxQJWpM1l1B0JnIaP8zG/baBtFLwR93kZKm3MabS
              z8pIqr/J04+HQR+VcLkCe7kaJc/sQlN5Ov6snGPvGenPkL5gMrD6
              -----END CERTIFICATE-----
            key: |
              -----BEGIN RSA PRIVATE KEY-----
              MIIEowIBAAKCAQEAragksFWulbJPWT/Unpbtg79pOLzsXF2RIyaUOD0HCk9QlrP8
              a5ojglzEvuNF8NVZeaj090nFRE51VnouqUgktnaHNwL3fuZcVyl5J66asiskPsfZ
              cxT5nOC1uIegQWa8bSiqnPRbQUX3QNFSzA9RmRSTjbRPzBm72Y2grV+vNYysuq1p
              8l/qs2GDJZTuLpMBYGrWxcmD6bgLy1UmgCzK58fFnMR8Muq+jCIPsSD1FMD3Q6FV
              MXi58pHufxl6UgmzbO0phs5SsBE0mhIX2OHx1VHsk/2OH4GKpOBppcyQLdtpxxfs
              X8Xg6gazVH5G6nT/rFVUM/S+4UJCOYydeQZ/QQIDAQABAoIBAAlb4n5OX9ZZgcVB
              l2fkonBTRIx2QhbIRCYs0hgl0ddQZvt4P8ZczEUeUswm24IbPXM9E9av9x2zTMeY
              ViNxa+kZgjgIxOXl7FwWNB1bX6LyiEWJ58I4AyvdQG3tgUmFC+qmImvLD4/5AVZQ
              8bFlsfQaE8mzSgmp6WHULDCr03mDQKAglJQ3oUWJFfqDQUDTf8SpRBw9S0WewpFX
              hs9BF6YPxcI6rFqNge8MAUXWeBkP8BQV4S59xtq3szK4ydVCJlSyKaUYpThHiBRU
              WU9VSyfA4t68ouUcSYDJ3boR9odYTYU2QdjQxYkOyyNvnqLE4kMP1x7+0zbxrKyy
              1LezzkECgYEA2AM1SHzFY35oIt8Lvd0nGkCZFJ8zI8JNPV7HeaJYyfj9MpRrKD5i
              2ZRDU1wZ97ML9gMwsTbasW0Nb6aLDQLdZI5boS8XfPRqGUTYkuPj+VzGRlmlx7We
              KDVZzPVoNd71H4rPPjfTDGyfoI9jpjyVGJWTuKy2UQgzU/9GP2cQzsUCgYEAzc20
              rEYKnpslMHe7puPG5RVOqIdRsyZmcaRbN9OwIguJELaPWx1GVkl8uCPCbZ1tmgnL
              AQRCnFhlC5JlggkDdYM1Kwq4HdszHMrmxewbEnzkLMdHtg0sQU6FRSM5HHXVaW/n
              6jyiD8p/aZWlo7H35DGRCFU8h4XJYJMGxa2b9k0CgYBSZqbkx/PkSEwhQUSRYNOR
              yCKdIz223l/okUc2tx93rGup58QYzfOXXF9yZSfivYJKjlz8vRgfpqIBfV590CH0
              QfniOryTBgmTKhgTsKs+bI2WOIxs6nMyk2d2MAdYxXxsU99KtLDlhGpALXKt715Q
              yn5XbEsADkjGOhLqDL70oQKBgDagx7iCzwbSv8hhv9nI1F6yjTKG2NTo+IBp1By5
              gCNJVJSvINZaqvT0hLqMI2vdQd6FgvE+JEBD5m5v6aneoqBqt445Ri4GpUabRS58
              QaNiq16Hdy2HyZt8MDvt4ZcAYCmgnrq6ZXozkiaApnsRHm/gCFNh7LM8e/u6iy2l
              q6RxAoGBAMa+VsZ2EPYQ+g9IFTydvkx0MZOL7b08z3F3875k+vU5EJOWanv5DF/f
              nIjRtpdOj7GZ4IZYyIAdBNlgPoCX6rc8mhQA4ehT0CN/D/xIkKIz76CtCVtUhE0P
              9vnayDhnZXJcT8dPkJHYucd+rydSy2PZUVU2LospQ+V9scuThRID
              -----END RSA PRIVATE KEY-----

  # Gardener controller manager configuration values
  controller:
    internalDomain:
      provider: unmanaged
      domain: nip.io
    config:
      server:
        http:
          bindAddress: 0.0.0.0
          port: 2718