{{- if and .Values.global.deployment.virtualGarden.enabled .Values.global.admission.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ required ".Values.global.admission.serviceAccountName is required" .Values.global.admission.serviceAccountName }}
  namespace: garden
  labels:
    app: gardener
    role: admission-controller
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
{{- end }}
