name: Import the newest gardener helmcharts

on:
  push:
    branches:
      - 'renovate/gardener-core'
    paths:
      - 'hack/helmchart-import/import-gardener-charts.py'

jobs:
  import:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          token: ${{ secrets.COMMIT_TOKEN }}
      - uses: actions/setup-python@v2
        with:
          python-version: '3.7'

      - name: Import gardener-core helmcharts and patch them
        run: |
          pip install -r hack/helmchart-import/requirements.txt
          python hack/helmchart-import/import-gardener-charts.py
          git apply hack/helmchart-import/patches/*.patch

      - name: Commit changes
        uses: EndBug/add-and-commit@v8
        with:
          author_name: 23t-machine-user
          author_email: 23t-machine-user@example.com
          message: 'Update the gardener helmcharts'
          add: -u
