name: Shift branches

on:
  pull_request:
    branches:
      - 'renovate/main-gardener'

jobs:
  shiftbranches:
    if: ${{ github.event.label.name == 'minor-update' }}
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Run branch-shift script
        run: hack/ci/shift-branches.sh
